#!/bin/bash

INFOBOX=${INFOBOX=dialog}
TITLE="Default"
MESSAGE="Something to say"
XCOORD=10
YCOORD=20


funcDisplayInfobox () {
	$INFOBOX --title "$1" --infobox "$2" "$3" "$4"
	sleep "$5"
}


if [ "$1" == "shutdown" ]; then
	funcDisplayInfobox "WARNING!" "We are shutting down the system..." "11" "21" "5"
	echo "Shutting down!"
else
	funcDisplayInfobox "Information..." "You are not doing anything..." "20" "40" "5"
	echo "Not doing anyhting"
fi 
