#!/bin/bash

INFOBOX=${INFOBOX=dialog}
TITLE="Default"
MESSAGE="Something to say"
XCOORD=10
YCOORD=20


funcDisplayMsgbox () {
	$INFOBOX --title "$1" --msgbox "$2" "$3" "$4"
}


if [ "$1" == "shutdown" ]; then
	funcDisplayMsgbox "WARNING!" "Please press OK when you're ready to shutdown" "11" "21"
	echo "Shutting down now!"
else
	funcDisplayMsgbox "Boring" "You are not doing anything..." "10" "20"
	echo "Not doing anyhting"
fi 
