#!/bin/bash


while [ "$CHOICE" != "Q" ] && [ "$CHOICE" != "q" ]; do
	echo "It's dangerous out there, choose one:"
	echo "================"
	echo "Chikorita"
	echo "Cyndaquil"
	echo "Totodile"
	echo "Quit (Q/q)"
	echo ""
	read CHOICE

done
